- action.php
- classes/task/duplicate_task.php
cb5e4332390a1b2a557903563d7caa88259b08b1 introduced a bug preventing the `duplicate_task` to properly deserialize the module records to be duplicated. As a consequence the task failed completely.
In addition to that I unified the syntax a little bit
> Fix duplicate task (de)serializing, adapt array/quote notation

- version.php
For the 7.0.0 release of the plugin I added the requirement for the current moodle 4.0 release version. Ideally, we could pull a release before the official moodle 4.0 release (April 19th) to acquire the early bird badge, of course only, if we do not find any bugs while testing.
@Syxton 
Speaking of testing: I cannot run behat tests in my dev environment currently in 4.0 for some reason I cannot tell (https://github.com/moodlehq/moodle-docker/issues/207). Can you doublecheck if the tests are passing in an environment with all course formats installed we are currently trying to support? Maybe even after merging #22? :-) Thanks in advance!
BTW: I tested basic formats topics, weekly and topcoll manually. Onetopic and tiles are still pretty buggy but have not been updated to 4.0 yet anyway, …
> Bump version for 4.0 release

- version.php
We should restrict the `39_311_stable` branch to the corresponding moodle versions. I also bumped up version for a release which includes the Mac OS fix.
> Restrict 39_311_stable branch to corresponding moodle versions

- templates/duplicateto_select.mustache
- templates/moveto_select.mustache
- templates/section_select.mustache
Following the suggestion of @jrchamp at https://github.com/Syxton/moodle-block_massaction/pull/26#issuecomment-1102712615
> Remove obsolete aria-label attributes

- block_massaction.php
This backports #38 to the `39_311_stable` branch
> Backport to 3.9-3.11: Fix check for applicable formats 

- block_massaction.php
There currently is a wrong check for showing the block content. This does not really hurt any functionality because the first part (the wrong one) of the expression always evaluates to true. This only triggers a debugger warning if the second part tries to access a non existing array key in case we have not defined the current course format in `applicable_formats`. However, this should be fixed.
Thanks @sh-csg for spotting and reporting this!
> Fix check for applicable formats

- block_massaction.php
- lang/en/block_massaction.php
Closes #42 
In rare cases users manage to add two blocks to a page despite block API saying this is not allowed.
For example: Load same course in two tabs, click "Add block" in both tabs. Then add a block in the first, after that in the second tab. Voilà: you got two block instances :-)
This also can happen when two editing teachers add a block at the same time, of course.
This PR does not prevent that issue (which has to be fixed in moodle core in my opinion). However: The block now refuses to display if it detects more than one instance of the massaction block on the current page displaying an error message to the user.
This PR could theoretically be backported to `39_311_stable` if necessary. However, to keep up the compatibility with moodle 3.9 stable including PHP <7.4 we would have …
> Ensure there is only one block instance on a page

- templates/block_massaction.mustache
Closes #46
Same screenshot than in #46 after patch:
> Fix alignment of action links

- .github/workflows/ci.yml
MDL-71747 - changes environmental requirements.  
This commit bumps the postgres version for automated testing to v12 from v10.  Fixes the failed master tests.
> Update ci.yml environmental requirements for 4.1+

- classes/actions.php
- tests/massaction_test.php
Closes #54
The bug results from moodle handling the stealth states differently in hidden sections:
It only uses the attribute "visible".
Also: I misunderstood the core course format API function `allow_stealth_module_visibility`: This does not return if the course format in general supports a stealth state, but if it at the moment does in the current section.
> Fix visibility actions for hidden sections

- tests/behat/grid.feature
- tests/behat/onetopic.feature
- tests/behat/tiles.feature
With the changes in current master and latest versions of format_tiles, format_grid and format_onetopic the behat tests fail. This fixes them.
> Fix behat tests for grid, onetopic, tiles

- tests/massaction_test.php
Creation of dynamic properties is deprecated in PHP 8.2 and will be removed in a future release.
> tests: define class properties (PHP 8.2)

- templates/duplicateto_select.mustache
- templates/moveto_select.mustache
Fix the issue #102
The issue is checking empty value in the error check but actual value is not empty when target is not chosen.
https://github.com/Syxton/moodle-block_massaction/blob/bfe404ea5734d89ff774e0c44e9b93498e16f70c/amd/src/massactionblock.js#L204
> Issue #102 Fix move/duplicate error when target is not chosen

- block_massaction.php
Show permission error if the user doesn't have permission.
> Issue #87 Do not display content if a user does not have permission

- templates/duplicateto_select.mustache
- templates/moveto_select.mustache
- templates/section_select.mustache
Fix the issue https://github.com/Syxton/moodle-block_massaction/issues/103
The issue is that section/activity name can be included special characters (e.g. "&"), but the template adds HTML escapes.
> Issue #103 Fix escaped text in dropdown

- .github/workflows/ci.yml
the` master` branch is now gone.
for reference, please see: https://moodle.org/mod/forum/discuss.php?d=452551
GHA run: https://github.com/stopfstedt/moodle-block_massaction/actions/runs/11824340971
> repair CI pipeline: renames target mainline Moodle branch.

- settings.php
If you have some course formats disabled here /admin/settings.php?section=manageformats , these formats are still displayed here : /admin/settings.php?section=blocksettingmassaction
This PR should prevent this issue.
> ignore disabled course formats

- classes/task/duplicate_task.php
Fix issue #122 to complete duplicate_task
> Issue #122 Complete duplicate_task

- classes/actions.php
- tests/behat/actions.feature
- tests/massaction_test.php
> fix for availability in hidden sections

- classes/actions.php
- tests/massaction_test.php
Fix for 
https://github.com/Syxton/moodle-block_massaction/issues/135
> Fix section checking
